# data
dataset: '../data/australian_cases.csv'
ref_file: '../reference.csv'
out_file: '../data/scores.csv'

# columns
timecol: 'date'
target: 'cases'
series: 'Province/State'

# project setup
metric: 'MAE'
backtests: 2
backtest_length: 7
fdw: -14
history: 28
horizon: 3
states: ['New South Wales', 'Victoria', 'Queensland', 'South Australia']

# deployment
description: 'Australian Coronavirus cases'

# retraining
accuracy_days: 3
run_autopilot: False
n_models: 5
